spring.application.name=makemytrip
server.port=8082
server.address=0.0.0.0
spring.data.mongodb.uri=mongodb+srv://shubham930:Kalawati%407488@main.y0couq3.mongodb.net/?appName=Main
spring.data.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
